name: HACS Validation

on:
  push:
  pull_request:

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with: { category: "integration" }
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"